---
apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: csantana-nodejs-git
spec:
  type: git
  params:
    - name: url
      value: https://github.com/csantanapr/appsody-sample-nodejs-express
---
apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: csantana-nodejs-image
spec:
  type: image
  params:
    - name: url
      value: docker-registry.default.svc:5000/csantana/appsody-sample-nodejs-express:tkn
---
apiVersion: tekton.dev/v1alpha1
kind: Pipeline
metadata:
  name: csantana-nodejs-pipeline
spec:
  resources:
    - name: git-source
      type: git
    - name: docker-image
      type: image
  tasks:
    - name: nodejs-express-test-build-task
      taskRef:
        name: csantana-nodejs-express-build-task
      resources:
        inputs:
          - name: git-source
            resource: git-source
        outputs:
          - name: docker-image
            resource: docker-image
