---
apiVersion: tekton.dev/v1alpha1
kind: Pipeline
metadata:
  name: nodejs-express-test-pipeline
spec:
  resources:
    - name: git-source
      type: git
  tasks:
    - name: test-task
      taskRef:
        name: nodejs-express-test-task
      resources:
        inputs:
          - name: git-source
            resource: git-source
