---
apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: csantana-nodejs-express-build-task
spec:
  inputs:
    resources:
      - name: git-source
        type: git
  steps:
    - name: npm-test
      image: kabanero/nodejs-express:0.2
      workingDir: /project
      command:
        [
          "/bin/bash",
          "-c",
          "cp -a ${inputs.resources.git-source.path}/* $APPSODY_WATCH_DIR && $APPSODY_INSTALL && echo $APPSODY_TEST >/tmp/test.sh && source /tmp/test.sh",
        ]
---
apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: csantana-nodejs-express-build-old
  namespace: kabanero
spec:
  inputs:
    params:
      - default: /workspace/extracted/Dockerfile
        name: pathToDockerFile
      - default: /workspace/extracted
        name: pathToContext
    resources:
      - name: git-source
        outputImageDir: ""
        targetPath: ""
        type: git
  outputs:
    resources:
      - name: docker-image
        outputImageDir: /builder/home/image-outputs/docker-image
        targetPath: ""
        type: image
  steps:
    - args:
        - -c
        - /extract.sh
      command:
        - /bin/bash
      env:
        - name: gitsource
          value: git-source
      image: appsody/appsody-buildah
      name: assemble-extract
      resources: {}
      securityContext:
        privileged: true
      volumeMounts:
        - mountPath: /var/lib/containers
          name: varlibcontainers
    - name: npm-test
      securityContext:
        privileged: true
      image: kabanero/nodejs-express:0.2
      command:
        [
          "/bin/bash",
          "-c",
          "cd ${inputs.params.pathToContext}/user-app && ls && npm install --prefix user-app && npm install -g mocha && cd .. && npm test && npm test --prefix user-app",
        ]
      env:
        - name: gitsource
          value: git-source
      volumeMounts:
        - mountPath: /var/lib/containers
          name: varlibcontainers
  volumes:
    - emptyDir: {}
      name: varlibcontainers
